/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/alert.vue')['default']
    Avatar: typeof import('./src/components/avatar.vue')['default']
    Badge: typeof import('./src/components/badge.vue')['default']
    BottomNavigation: typeof import('./src/components/bottom-navigation.vue')['default']
    Breadcrumbs: typeof import('./src/components/breadcrumbs.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    Carousel: typeof import('./src/components/carousel.vue')['default']
    Chat: typeof import('./src/components/chat.vue')['default']
    Checkbox: typeof import('./src/components/checkbox.vue')['default']
    Collapse: typeof import('./src/components/collapse.vue')['default']
    Countdown: typeof import('./src/components/countdown.vue')['default']
    Diff: typeof import('./src/components/diff.vue')['default']
    Divider: typeof import('./src/components/divider.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    Dropdown: typeof import('./src/components/dropdown.vue')['default']
    FileInput: typeof import('./src/components/file-input.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Hero: typeof import('./src/components/hero.vue')['default']
    Indicator: typeof import('./src/components/indicator.vue')['default']
    Input: typeof import('./src/components/input.vue')['default']
    Join: typeof import('./src/components/join.vue')['default']
    Kbd: typeof import('./src/components/kbd.vue')['default']
    Link: typeof import('./src/components/link.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Mask: typeof import('./src/components/mask.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Progress: typeof import('./src/components/progress.vue')['default']
    RadialProgress: typeof import('./src/components/radial-progress.vue')['default']
    Radio: typeof import('./src/components/radio.vue')['default']
    Range: typeof import('./src/components/range.vue')['default']
    Rating: typeof import('./src/components/rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select.vue')['default']
    Skeleton: typeof import('./src/components/skeleton.vue')['default']
    Stack: typeof import('./src/components/stack.vue')['default']
    Stat: typeof import('./src/components/stat.vue')['default']
    Steps: typeof import('./src/components/steps.vue')['default']
    Swap: typeof import('./src/components/swap.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
    Table: typeof import('./src/components/table.vue')['default']
    Textarea: typeof import('./src/components/textarea.vue')['default']
    Timeline: typeof import('./src/components/timeline.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
    Toggle: typeof import('./src/components/toggle.vue')['default']
    Tooltip: typeof import('./src/components/tooltip.vue')['default']
  }
}
