export const components = {
  Button: 'Button 按钮',
  // Dropdown: 'Dropdown 下拉菜单',
  // Modal: 'Modal 对话框',
  Swap: 'Swap 调换',
  // 'Data display': '数据展示',
  // Accordion: 'Accordion 手风琴',
  Alert: 'Alert 警告提示',
  Avatar: 'Avatar 头像',
  Badge: 'Badge 徽章',
  Card: 'Card 卡片',
  Carousel: 'Carousel 轮播',
  'Chat bubble': 'Chat bubble 聊天气泡',
  Collapse: 'Collapse 折叠面板',
  Countdown: 'Countdown 计数',
  Kbd: 'Kbd 键盘',
  Loading: 'Loading 加载',
  Progress: 'Progress 进度条',
  'Radial progress': 'Radial progress 圆形进度条',
  // Stat: 'Stat 统计展示',
  // Table: 'Table 表格',
  Tooltip: 'Tooltip 文字提示',
  'Data input': '数据输入',
  Checkbox: 'Checkbox 复选框',
  'Text input': 'Text input 文字输入框',
  Radio: 'Radio 单选框',
  Range: 'Range 范围滑块',
  Rating: 'Rating 评分',
  Select: 'Select 选择器',
  Textarea: 'Textarea 多行文本框',
  Toggle: 'Toggle 开关',
  Layout: '布局',
  Artboard: 'Artboard 画板',
  'Button group': 'Button group 按钮组',
  Divider: 'Divider 分隔线',
  Drawer: 'Drawer 抽屉',
  Footer: 'Footer 页脚',
  Hero: 'Hero',
  Indicator: 'Indicator 标志',
  'Input group': 'Input group 输入框组',
  Mask: 'Mask 遮罩',
  Stack: 'Stack 堆叠',
  Toast: 'Toast',
  // Navigation: '导航栏',
  // Breadcrumbs: 'Breadcrumbs 面包屑导航',
  // 'Bottom navigation': 'Bottom navigation 底部导航栏',
  Link: 'Link 链接',
  Menu: 'Menu 菜单',
  // Navbar: 'Navbar 导航栏',
  // Pagination: 'Pagination 分页',
  Steps: 'Steps 步骤条',
  Tab: 'Tab 选项卡'
  // Mockup: '模型',
  // Browser: 'Browser 浏览器',
  // Code: 'Code 代码',
  // Phone: 'Phone 手机',
  // Window: 'Window 视窗'
}
